# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesteLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testeLogin(self):
    self.driver.get("https://www.huggy.app/?return=https%3A%2F%2Flegacy.huggy.app%2Fpanel%2F")
    self.driver.set_window_size(945, 1060)
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.ID, "input_11").click()
    self.driver.find_element(By.ID, "input_11").send_keys("leonardo.henriques@bradvisors.com.br")
    self.driver.find_element(By.CSS_SELECTOR, ".Button_button_3qErG:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_button_3qErG:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "input_17").click()
    self.driver.find_element(By.ID, "input_17").send_keys("Bra123456")
    self.driver.find_element(By.CSS_SELECTOR, ".Button_block_2cQNN").click()
    
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_block_2cQNN")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, "#menubar-config > .module_3KJrf > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#menubar-config > .module_3KJrf > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Canais").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(7) .name_1FeST").click()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, ".htable-column-label:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-item:nth-child(9) .ms-choice > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-item:nth-child(9) li:nth-child(22) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hgs-right > .btn").click()
  
